# drivers/sensors/Makefile
#
# Copyright (C) 2013 Samsung Electronics Co, Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

obj-$(CONFIG_SENSORS)	+= sensors_core.o
obj-$(CONFIG_SENSORS_GP2A002S)	+= gp2a.o
obj-$(CONFIG_SENSORS_GP2AP020A00F) += gp2ap020.o
obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2_driver.o bst_sensor_common.o
obj-$(CONFIG_SENSORS_BMM050)	+= bmm050_driver.o bmm050.o
obj-$(CONFIG_SENSORS_BMA254)	+= bma254_driver.o
obj-$(CONFIG_SENSORS_TMD27723)	+= tmd27723.o
obj-$(CONFIG_SENSORS_GRIP_SX9500)		+= sx9500.o
obj-$(CONFIG_SENSORS_ACCELOMETER_BMA25X)	+= bma255.o
