obj-y	+= sec_charger.o	\
		sec_fuelgauge.o     \
		sec_dt_init.o	\
				sec_battery.o

obj-$(CONFIG_FUELGAUGE_MAX17042)	+= max17042_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17048)	+= max17048_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17050)	+= max17050_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_STC3115)		+= stc3115_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_D2199)		+= d2199_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_88PM822)		+= 88pm80x_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_88PM800)     += 88pm80x_fuelgauge.o

obj-$(CONFIG_CHARGER_MAX8903)	+= max8903_charger.o
obj-$(CONFIG_CHARGER_SMB328)	+= smb328_charger.o
obj-$(CONFIG_CHARGER_SMB347)	+= smb347_charger.o
obj-$(CONFIG_CHARGER_SMB358)	+= smb358_charger.o
obj-$(CONFIG_CHARGER_BQ24157)	+= bq24157_charger.o
obj-$(CONFIG_CHARGER_BQ24190)	+= bq24190_charger.o
obj-$(CONFIG_CHARGER_BQ24191)	+= bq24190_charger.o
obj-$(CONFIG_CHARGER_NCP1851)	+= ncp1851_charger.o
obj-$(CONFIG_CHARGER_RT9455)	+= rt9455_charger.o
obj-$(CONFIG_CHARGER_SM5414)   += sm5414_charger.o
