# Makefile for MARVELL MMP ISP driver

obj-$(CONFIG_VIDEO_MMPISP_SENSOR) += mvisp_sensor.o
obj-$(CONFIG_VIDEO_MMPISP) += socisp-pdev.o socisp-mdev.o socisp-vdev.o

# TODO: Add Camera/ISP IP driver below

obj-$(CONFIG_VIDEO_MMPISP_AREA51) += ispdma.o ispccic.o isp.o
