ccflags-y := -Idrivers/staging/android -Idrivers/clk/mmp
obj-$(CONFIG_MMP_DISP_CONTROLLER)  += mmp_ctrl.o mmp_dsi.o vsync.o debug.o mmp_vdma.o mmp_apical.o shadow.o
obj-$(CONFIG_MMP_DISP_SPI)	   += mmp_spi.o
obj-$(CONFIG_MMP_DISP_DFC)	   += dfc.o
